apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: spring-on-aks
  labels:
    app: order-service
spec:
  selector:
    app: order-service
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: spring-on-aks
  labels:
    app: order-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: acraksapps1.azurecr.io/spring/order:v0.0.1
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        ports:
        - containerPort: 8080
        env:
        - name: EUREKA_HOST
          value: "service-discovery"
        - name: EUREKA_PORT
          value: "8761"
