apiVersion: v1
kind: Service
metadata:
  name: service-discovery
spec:
  selector:
    app: service-discovery
  ports:
  - port: 8761
    targetPort: 8761


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-discovery
  namespace: spring-on-aks
  labels:
    app: service-discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-discovery
  template:
    metadata:
      labels:
        app: service-discovery
    spec:
      containers:
      - name: service-discovery
        imagePullPolicy: Always
        image: acraksapps1.azurecr.io/spring/eurekaserver:v1.0.0
        ports:
        - containerPort: 8761
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"