apiVersion: v1
kind: Service
metadata:
  name: warehouse-service
  namespace: spring-on-aks
  labels:
    app: warehouse-service
spec:
  selector:
    app: warehouse-service
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: warehouse-service
  namespace: spring-on-aks
  labels:
    app: warehouse-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: warehouse-service
  template:
    metadata:
      labels:
        app: warehouse-service
    spec:
      containers:
      - name: warehouse-service
        imagePullPolicy: Always
        image: acraksapps1.azurecr.io/spring/warehouse-service:v0.0.1
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        ports:
        - containerPort: 9090
        env:
        - name: EUREKA_HOST
          value: "service-discovery"
        - name: EUREKA_PORT
          value: "8761"
